/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "//": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                message: string;
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        companyName: string;
                        /** Format: email */
                        userEmail: string;
                        password: string;
                        referralCode?: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                user: {
                                    userId: string;
                                    email: string;
                                    companyId: string;
                                };
                                company: {
                                    companyName: string;
                                    companyId: string;
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    email: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: unknown;
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: unknown;
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                user: {
                                    userId: string;
                                    referralCode: string;
                                    companyId: string;
                                    /** @enum {string|null} */
                                    contractorType: "general" | "painter" | "plumber" | "electrician" | "carpenter" | "mason" | "landscaper" | "handyman" | "drywaller" | "framer" | "tileSetter" | "roofer" | "sidingInstaller" | "windowInstaller" | "doorInstaller" | "other";
                                    email: string;
                                    emailVerified: boolean;
                                    phoneNumber: string | null;
                                    phoneVerified: boolean;
                                    /** @enum {string|null} */
                                    preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                    firstName: string | null;
                                    lastName: string | null;
                                    is2FAEnabled: boolean | null;
                                    /** @enum {string|null} */
                                    lockReason: "tooManyFailedTFA" | "passwordResetCooldown";
                                    createdAt: string;
                                    /** @enum {string|null} */
                                    role: "admin" | "standard" | "view-only";
                                    linkedGoogleAccount: boolean;
                                };
                                company: {
                                    companyId: string;
                                    companyName: string;
                                    email: string | null;
                                    phoneNumber: string | null;
                                    addressLine1: string | null;
                                    addressLine2: string | null;
                                    city: string | null;
                                    state: string | null;
                                    postalCode: string | null;
                                    notes: string | null;
                                    metadata: {
                                        [key: string]: unknown;
                                    } | null;
                                    createdAt: string;
                                    updatedAt: string;
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        firstName?: string;
                        lastName?: string;
                        /** Format: email */
                        email?: string;
                        phoneNumber?: string;
                        /** @enum {string} */
                        preferredContactMethod?: "email" | "phone" | "sms" | "whatsapp";
                        /** @enum {string} */
                        contractorType?: "general" | "painter" | "plumber" | "electrician" | "carpenter" | "mason" | "landscaper" | "handyman" | "drywaller" | "framer" | "tileSetter" | "roofer" | "sidingInstaller" | "windowInstaller" | "doorInstaller" | "other";
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                user: {
                                    userId: string;
                                    referralCode: string;
                                    companyId: string;
                                    /** @enum {string|null} */
                                    contractorType: "general" | "painter" | "plumber" | "electrician" | "carpenter" | "mason" | "landscaper" | "handyman" | "drywaller" | "framer" | "tileSetter" | "roofer" | "sidingInstaller" | "windowInstaller" | "doorInstaller" | "other";
                                    email: string;
                                    emailVerified: boolean;
                                    phoneNumber: string | null;
                                    phoneVerified: boolean;
                                    /** @enum {string|null} */
                                    preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                    firstName: string | null;
                                    lastName: string | null;
                                    is2FAEnabled: boolean | null;
                                    /** @enum {string|null} */
                                    lockReason: "tooManyFailedTFA" | "passwordResetCooldown";
                                    createdAt: string;
                                    /** @enum {string|null} */
                                    role: "admin" | "standard" | "view-only";
                                    linkedGoogleAccount: boolean;
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/me/test-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: unknown;
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        to: string;
                        subject: string;
                        firstName: string;
                        body: string;
                        /** Format: email */
                        replyTo?: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                message: string;
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        type: "verify_email" | "verify_phone";
                        otp: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: unknown;
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/send-verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: unknown;
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                        otp?: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                token?: string;
                                require2FA: boolean;
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login-user/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: unknown;
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: unknown;
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                jobs: {
                                    jobId: string;
                                    companyId: string;
                                    customerId: string;
                                    jobNumber: string | null;
                                    title: string;
                                    description: string | null;
                                    /** @enum {string} */
                                    status: "planned" | "in-progress" | "on-hold" | "completed" | "cancelled";
                                    estimatedStartDate: string | null;
                                    estimatedEndDate: string | null;
                                    actualStartDate: string | null;
                                    actualEndDate: string | null;
                                    addressLine1: string | null;
                                    addressLine2: string | null;
                                    city: string | null;
                                    state: string | null;
                                    postalCode: string | null;
                                    country: string | null;
                                    metadata: {
                                        [key: string]: unknown;
                                    } | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt: string | null;
                                    price: number | null;
                                    customer: {
                                        customerId: string;
                                        companyId: string;
                                        firstName: string;
                                        lastName: string;
                                        email: string;
                                        phoneNumber: string | null;
                                        /** @enum {string|null} */
                                        preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                        addressLine1: string;
                                        addressLine2: string | null;
                                        city: string;
                                        state: string;
                                        postalCode: string;
                                        notes: string | null;
                                        metadata: {
                                            [key: string]: unknown;
                                        } | null;
                                        createdAt: string;
                                        updatedAt: string;
                                        deletedAt: string | null;
                                    };
                                    paymentDraws: {
                                        paymentDrawId: string;
                                        jobId: string;
                                        paymentAmount: number;
                                        expectedPaymentDate: string;
                                        actualPaymentDate: string | null;
                                        dateRequested: string | null;
                                        /** @enum {string} */
                                        status: "future" | "requested" | "paid";
                                        description: string | null;
                                        images: string[];
                                        createdAt: string;
                                        updatedAt: string;
                                    }[];
                                }[];
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        customerId: string;
                        title: string;
                        description?: string;
                        jobNumber?: string;
                        /** @enum {string} */
                        status?: "planned" | "in-progress" | "on-hold" | "completed" | "cancelled";
                        /** Format: date-time */
                        estimatedStartDate?: string;
                        /** Format: date-time */
                        estimatedEndDate?: string;
                        addressLine1?: string;
                        addressLine2?: string;
                        city?: string;
                        state?: string;
                        postalCode?: string;
                        country?: string;
                        metadata?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                job: {
                                    jobId: string;
                                    companyId: string;
                                    customerId: string;
                                    jobNumber: string | null;
                                    title: string;
                                    description: string | null;
                                    /** @enum {string} */
                                    status: "planned" | "in-progress" | "on-hold" | "completed" | "cancelled";
                                    estimatedStartDate: string | null;
                                    estimatedEndDate: string | null;
                                    actualStartDate: string | null;
                                    actualEndDate: string | null;
                                    addressLine1: string | null;
                                    addressLine2: string | null;
                                    city: string | null;
                                    state: string | null;
                                    postalCode: string | null;
                                    country: string | null;
                                    metadata: {
                                        [key: string]: unknown;
                                    } | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt: string | null;
                                    customer: {
                                        customerId: string;
                                        companyId: string;
                                        firstName: string;
                                        lastName: string;
                                        email: string;
                                        phoneNumber: string | null;
                                        /** @enum {string|null} */
                                        preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                        addressLine1: string;
                                        addressLine2: string | null;
                                        city: string;
                                        state: string;
                                        postalCode: string;
                                        notes: string | null;
                                        metadata: {
                                            [key: string]: unknown;
                                        } | null;
                                        createdAt: string;
                                        updatedAt: string;
                                        deletedAt: string | null;
                                    };
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        customerId?: string;
                        title?: string;
                        description?: string;
                        jobNumber?: string;
                        /** @enum {string} */
                        status?: "planned" | "in-progress" | "on-hold" | "completed" | "cancelled";
                        /** Format: date-time */
                        estimatedStartDate?: string | null;
                        /** Format: date-time */
                        estimatedEndDate?: string | null;
                        /** Format: date-time */
                        actualStartDate?: string | null;
                        /** Format: date-time */
                        actualEndDate?: string | null;
                        addressLine1?: string | null;
                        addressLine2?: string | null;
                        city?: string | null;
                        state?: string | null;
                        postalCode?: string | null;
                        country?: string | null;
                        metadata?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                job: {
                                    jobId: string;
                                    companyId: string;
                                    customerId: string;
                                    jobNumber: string | null;
                                    title: string;
                                    description: string | null;
                                    /** @enum {string} */
                                    status: "planned" | "in-progress" | "on-hold" | "completed" | "cancelled";
                                    estimatedStartDate: string | null;
                                    estimatedEndDate: string | null;
                                    actualStartDate: string | null;
                                    actualEndDate: string | null;
                                    addressLine1: string | null;
                                    addressLine2: string | null;
                                    city: string | null;
                                    state: string | null;
                                    postalCode: string | null;
                                    country: string | null;
                                    metadata: {
                                        [key: string]: unknown;
                                    } | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt: string | null;
                                    customer: {
                                        customerId: string;
                                        companyId: string;
                                        firstName: string;
                                        lastName: string;
                                        email: string;
                                        phoneNumber: string | null;
                                        /** @enum {string|null} */
                                        preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                        addressLine1: string;
                                        addressLine2: string | null;
                                        city: string;
                                        state: string;
                                        postalCode: string;
                                        notes: string | null;
                                        metadata: {
                                            [key: string]: unknown;
                                        } | null;
                                        createdAt: string;
                                        updatedAt: string;
                                        deletedAt: string | null;
                                    };
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/jobs/scopeofwork/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                scopeOfWork: {
                                    scopeOfWorkId: string;
                                    contractorId: string;
                                    jobId: string;
                                    notes: string | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    lineItems: {
                                        sowLineItemId: string;
                                        scopeOfWorkId: string;
                                        description: string;
                                        price: number | null;
                                        startDate: string | null;
                                        endDate: string | null;
                                        contractor: string | null;
                                        isAllocation: boolean;
                                        sortOrder: number;
                                        createdAt: string;
                                        updatedAt: string;
                                    }[];
                                } | null;
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        lineItems: {
                            description: string;
                            price?: number | null;
                            startDate?: string | null;
                            endDate?: string | null;
                            contractor?: string | null;
                            isAllocation: boolean;
                            sortOrder?: number;
                        }[];
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                scopeOfWork: {
                                    scopeOfWorkId: string;
                                    contractorId: string;
                                    jobId: string;
                                    notes: string | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    lineItems: {
                                        sowLineItemId: string;
                                        scopeOfWorkId: string;
                                        description: string;
                                        price: number | null;
                                        startDate: string | null;
                                        endDate: string | null;
                                        contractor: string | null;
                                        isAllocation: boolean;
                                        sortOrder: number;
                                        createdAt: string;
                                        updatedAt: string;
                                    }[];
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        lineItems: {
                            description: string;
                            price?: number | null;
                            startDate?: string | null;
                            endDate?: string | null;
                            contractor?: string | null;
                            isAllocation: boolean;
                            sortOrder?: number;
                        }[];
                        notes: string | null;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                scopeOfWork: {
                                    scopeOfWorkId: string;
                                    contractorId: string;
                                    jobId: string;
                                    notes: string | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    lineItems: {
                                        sowLineItemId: string;
                                        scopeOfWorkId: string;
                                        description: string;
                                        price: number | null;
                                        startDate: string | null;
                                        endDate: string | null;
                                        contractor: string | null;
                                        isAllocation: boolean;
                                        sortOrder: number;
                                        createdAt: string;
                                        updatedAt: string;
                                    }[];
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/jobs/scopeofwork/pdf/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                filename: string;
                                buffer?: unknown;
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/scopeofwork/reorder/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        lineItems: {
                            sowLineItemId: string;
                            sortOrder: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                success: boolean;
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/jobs/changeorders/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                changeOrders: {
                                    changeOrderId: string;
                                    jobId: string;
                                    title: string;
                                    lineItems: {
                                        description: string;
                                        price?: number | null;
                                        isAllocation: boolean;
                                    }[];
                                    notes: string | null;
                                    /** @enum {string} */
                                    status: "created" | "paymentRequested" | "paid";
                                    createdAt: string;
                                    updatedAt: string;
                                }[];
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                        lineItems: {
                            description: string;
                            price?: number | null;
                            isAllocation: boolean;
                        }[];
                        notes?: string;
                        /** @enum {string} */
                        status?: "created" | "paymentRequested" | "paid";
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                changeOrder: {
                                    changeOrderId: string;
                                    jobId: string;
                                    title: string;
                                    lineItems: {
                                        description: string;
                                        price?: number | null;
                                        isAllocation: boolean;
                                    }[];
                                    notes: string | null;
                                    /** @enum {string} */
                                    status: "created" | "paymentRequested" | "paid";
                                    createdAt: string;
                                    updatedAt: string;
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/changeorders/{jobId}/{changeOrderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                    changeOrderId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string | null;
                        lineItems?: {
                            description: string;
                            price?: number | null;
                            isAllocation: boolean;
                        }[];
                        notes?: string | null;
                        /** @enum {string} */
                        status?: "created" | "paymentRequested" | "paid";
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                changeOrder: {
                                    changeOrderId: string;
                                    jobId: string;
                                    title: string;
                                    lineItems: {
                                        description: string;
                                        price?: number | null;
                                        isAllocation: boolean;
                                    }[];
                                    notes: string | null;
                                    /** @enum {string} */
                                    status: "created" | "paymentRequested" | "paid";
                                    createdAt: string;
                                    updatedAt: string;
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/jobs/paymentdraws/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        paymentAmount: number;
                        /** Format: date-time */
                        expectedPaymentDate: string;
                        /** Format: date-time */
                        actualPaymentDate?: string | null;
                        /** Format: date-time */
                        dateRequested?: string | null;
                        /** @enum {string} */
                        status?: "future" | "requested" | "paid";
                        description?: string | null;
                        images?: string[];
                        shouldNotifyCustomer?: boolean;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                paymentDraw: {
                                    paymentDrawId: string;
                                    jobId: string;
                                    paymentAmount: number;
                                    expectedPaymentDate: string;
                                    actualPaymentDate: string | null;
                                    dateRequested: string | null;
                                    /** @enum {string} */
                                    status: "future" | "requested" | "paid";
                                    description: string | null;
                                    images: string[];
                                    createdAt: string;
                                    updatedAt: string;
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/paymentdraws/:paymentDrawId/{jobId}/{paymentDrawId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                    paymentDrawId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        paymentAmount?: number;
                        /** Format: date-time */
                        expectedPaymentDate?: string;
                        /** Format: date-time */
                        actualPaymentDate?: string | null;
                        /** Format: date-time */
                        dateRequested?: string | null;
                        /** @enum {string} */
                        status?: "future" | "requested" | "paid";
                        description?: string | null;
                        images?: string[];
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                paymentDraw: {
                                    paymentDrawId: string;
                                    jobId: string;
                                    paymentAmount: number;
                                    expectedPaymentDate: string;
                                    actualPaymentDate: string | null;
                                    dateRequested: string | null;
                                    /** @enum {string} */
                                    status: "future" | "requested" | "paid";
                                    description: string | null;
                                    images: string[];
                                    createdAt: string;
                                    updatedAt: string;
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/jobs/clientuploads/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    uploadType?: string;
                };
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                documents: {
                                    clientUploadId: string;
                                    jobId: string;
                                    s3Path: string;
                                    fileName: string;
                                    fileType: string;
                                    notes: string | null;
                                    /** @enum {string} */
                                    uploadType: "jobDocument" | "jobPhoto" | "jobContract";
                                    createdAt: string;
                                    updatedAt: string;
                                    documentUrl: string;
                                }[];
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        fileName: string;
                        fileType: string;
                        fileData: string;
                        notes?: string | null;
                        /** @enum {string} */
                        uploadType?: "jobDocument" | "jobPhoto" | "jobContract";
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                document: {
                                    clientUploadId: string;
                                    jobId: string;
                                    s3Path: string;
                                    fileName: string;
                                    fileType: string;
                                    notes: string | null;
                                    /** @enum {string} */
                                    uploadType: "jobDocument" | "jobPhoto" | "jobContract";
                                    createdAt: string;
                                    updatedAt: string;
                                    documentUrl: string;
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/clientuploads/{jobId}/{clientUploadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                    clientUploadId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                message: string;
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                customers: {
                                    customerId: string;
                                    companyId: string;
                                    firstName: string;
                                    lastName: string;
                                    email: string;
                                    phoneNumber: string | null;
                                    /** @enum {string|null} */
                                    preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                    addressLine1: string;
                                    addressLine2: string | null;
                                    city: string;
                                    state: string;
                                    postalCode: string;
                                    notes: string | null;
                                    metadata: {
                                        [key: string]: unknown;
                                    } | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt: string | null;
                                }[];
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        firstName: string;
                        lastName: string;
                        /** Format: email */
                        email: string;
                        phoneNumber?: string;
                        /** @enum {string} */
                        preferredContactMethod?: "email" | "phone" | "sms" | "whatsapp";
                        addressLine1: string;
                        addressLine2?: string;
                        city: string;
                        state: string;
                        postalCode: string;
                        notes?: string;
                        metadata?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                customer: {
                                    customerId: string;
                                    companyId: string;
                                    firstName: string;
                                    lastName: string;
                                    email: string;
                                    phoneNumber: string | null;
                                    /** @enum {string|null} */
                                    preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                    addressLine1: string;
                                    addressLine2: string | null;
                                    city: string;
                                    state: string;
                                    postalCode: string;
                                    notes: string | null;
                                    metadata: {
                                        [key: string]: unknown;
                                    } | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt: string | null;
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/:customerId/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    customerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        firstName?: string;
                        lastName?: string;
                        /** Format: email */
                        email?: string;
                        phoneNumber?: string | null;
                        /** @enum {string|null} */
                        preferredContactMethod?: "email" | "phone" | "sms" | "whatsapp";
                        addressLine1?: string;
                        addressLine2?: string | null;
                        city?: string;
                        state?: string;
                        postalCode?: string;
                        notes?: string | null;
                        metadata?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                customer: {
                                    customerId: string;
                                    companyId: string;
                                    firstName: string;
                                    lastName: string;
                                    email: string;
                                    phoneNumber: string | null;
                                    /** @enum {string|null} */
                                    preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                    addressLine1: string;
                                    addressLine2: string | null;
                                    city: string;
                                    state: string;
                                    postalCode: string;
                                    notes: string | null;
                                    metadata: {
                                        [key: string]: unknown;
                                    } | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt: string | null;
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                bids: {
                                    bidId: string;
                                    companyId: string;
                                    customerId: string;
                                    title: string;
                                    description: string | null;
                                    /** @enum {string} */
                                    status: "in-progress" | "sent-to-client" | "bid-lost" | "bid-won";
                                    estimatedStartDate: string | null;
                                    estimatedEndDate: string | null;
                                    addressLine1: string | null;
                                    addressLine2: string | null;
                                    city: string | null;
                                    state: string | null;
                                    postalCode: string | null;
                                    country: string | null;
                                    notes: string | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt: string | null;
                                    lineItems: {
                                        bidLineItemId: string;
                                        bidId: string;
                                        description: string;
                                        price: number | null;
                                        startDate: string | null;
                                        endDate: string | null;
                                        contractor: string | null;
                                        isAllocation: boolean;
                                        sortOrder: number;
                                        createdAt: string;
                                        updatedAt: string;
                                    }[];
                                    customer: {
                                        customerId: string;
                                        companyId: string;
                                        firstName: string;
                                        lastName: string;
                                        email: string;
                                        phoneNumber: string | null;
                                        /** @enum {string|null} */
                                        preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                        addressLine1: string;
                                        addressLine2: string | null;
                                        city: string;
                                        state: string;
                                        postalCode: string;
                                        notes: string | null;
                                        metadata: {
                                            [key: string]: unknown;
                                        } | null;
                                        createdAt: string;
                                        updatedAt: string;
                                        deletedAt: string | null;
                                    };
                                }[];
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        customerId: string;
                        title: string;
                        description?: string;
                        /** @enum {string} */
                        status?: "in-progress" | "sent-to-client" | "bid-lost" | "bid-won";
                        /** Format: date-time */
                        estimatedStartDate?: string;
                        /** Format: date-time */
                        estimatedEndDate?: string;
                        price?: number;
                        addressLine1?: string;
                        addressLine2?: string;
                        city?: string;
                        state?: string;
                        postalCode?: string;
                        country?: string;
                        lineItems?: {
                            description: string;
                            price?: number | null;
                            startDate?: string | null;
                            endDate?: string | null;
                            contractor?: string | null;
                            isAllocation: boolean;
                            sortOrder?: number;
                        }[];
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                bid: {
                                    bidId: string;
                                    companyId: string;
                                    customerId: string;
                                    title: string;
                                    description: string | null;
                                    /** @enum {string} */
                                    status: "in-progress" | "sent-to-client" | "bid-lost" | "bid-won";
                                    estimatedStartDate: string | null;
                                    estimatedEndDate: string | null;
                                    addressLine1: string | null;
                                    addressLine2: string | null;
                                    city: string | null;
                                    state: string | null;
                                    postalCode: string | null;
                                    country: string | null;
                                    notes: string | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt: string | null;
                                    lineItems: {
                                        bidLineItemId: string;
                                        bidId: string;
                                        description: string;
                                        price: number | null;
                                        startDate: string | null;
                                        endDate: string | null;
                                        contractor: string | null;
                                        isAllocation: boolean;
                                        sortOrder: number;
                                        createdAt: string;
                                        updatedAt: string;
                                    }[];
                                    customer: {
                                        customerId: string;
                                        companyId: string;
                                        firstName: string;
                                        lastName: string;
                                        email: string;
                                        phoneNumber: string | null;
                                        /** @enum {string|null} */
                                        preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                        addressLine1: string;
                                        addressLine2: string | null;
                                        city: string;
                                        state: string;
                                        postalCode: string;
                                        notes: string | null;
                                        metadata: {
                                            [key: string]: unknown;
                                        } | null;
                                        createdAt: string;
                                        updatedAt: string;
                                        deletedAt: string | null;
                                    };
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bids/{bidId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bidId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                message: string;
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bidId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        customerId?: string;
                        title?: string;
                        description?: string;
                        /** @enum {string} */
                        status?: "in-progress" | "sent-to-client" | "bid-lost" | "bid-won";
                        /** Format: date-time */
                        estimatedStartDate?: string | null;
                        /** Format: date-time */
                        estimatedEndDate?: string | null;
                        price?: number | null;
                        addressLine1?: string | null;
                        addressLine2?: string | null;
                        city?: string | null;
                        state?: string | null;
                        postalCode?: string | null;
                        country?: string | null;
                        lineItems?: {
                            description: string;
                            price?: number | null;
                            startDate?: string | null;
                            endDate?: string | null;
                            contractor?: string | null;
                            isAllocation: boolean;
                            sortOrder?: number;
                        }[];
                        notes?: string | null;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                bid: {
                                    bidId: string;
                                    companyId: string;
                                    customerId: string;
                                    title: string;
                                    description: string | null;
                                    /** @enum {string} */
                                    status: "in-progress" | "sent-to-client" | "bid-lost" | "bid-won";
                                    estimatedStartDate: string | null;
                                    estimatedEndDate: string | null;
                                    addressLine1: string | null;
                                    addressLine2: string | null;
                                    city: string | null;
                                    state: string | null;
                                    postalCode: string | null;
                                    country: string | null;
                                    notes: string | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt: string | null;
                                    lineItems: {
                                        bidLineItemId: string;
                                        bidId: string;
                                        description: string;
                                        price: number | null;
                                        startDate: string | null;
                                        endDate: string | null;
                                        contractor: string | null;
                                        isAllocation: boolean;
                                        sortOrder: number;
                                        createdAt: string;
                                        updatedAt: string;
                                    }[];
                                    customer: {
                                        customerId: string;
                                        companyId: string;
                                        firstName: string;
                                        lastName: string;
                                        email: string;
                                        phoneNumber: string | null;
                                        /** @enum {string|null} */
                                        preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                        addressLine1: string;
                                        addressLine2: string | null;
                                        city: string;
                                        state: string;
                                        postalCode: string;
                                        notes: string | null;
                                        metadata: {
                                            [key: string]: unknown;
                                        } | null;
                                        createdAt: string;
                                        updatedAt: string;
                                        deletedAt: string | null;
                                    };
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/bids/reorder/{bidId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bidId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        lineItems: {
                            bidLineItemId: string;
                            sortOrder: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                success: boolean;
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/bids/bid-won/{bidId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bidId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                bid: {
                                    bidId: string;
                                    companyId: string;
                                    customerId: string;
                                    title: string;
                                    description: string | null;
                                    /** @enum {string} */
                                    status: "in-progress" | "sent-to-client" | "bid-lost" | "bid-won";
                                    estimatedStartDate: string | null;
                                    estimatedEndDate: string | null;
                                    addressLine1: string | null;
                                    addressLine2: string | null;
                                    city: string | null;
                                    state: string | null;
                                    postalCode: string | null;
                                    country: string | null;
                                    notes: string | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt: string | null;
                                };
                                job: {
                                    jobId: string;
                                    companyId: string;
                                    customerId: string;
                                    jobNumber: string | null;
                                    title: string;
                                    description: string | null;
                                    /** @enum {string} */
                                    status: "planned" | "in-progress" | "on-hold" | "completed" | "cancelled";
                                    estimatedStartDate: string | null;
                                    estimatedEndDate: string | null;
                                    actualStartDate: string | null;
                                    actualEndDate: string | null;
                                    addressLine1: string | null;
                                    addressLine2: string | null;
                                    city: string | null;
                                    state: string | null;
                                    postalCode: string | null;
                                    country: string | null;
                                    metadata: {
                                        [key: string]: unknown;
                                    } | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    deletedAt: string | null;
                                    customer: {
                                        customerId: string;
                                        companyId: string;
                                        firstName: string;
                                        lastName: string;
                                        email: string;
                                        phoneNumber: string | null;
                                        /** @enum {string|null} */
                                        preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                        addressLine1: string;
                                        addressLine2: string | null;
                                        city: string;
                                        state: string;
                                        postalCode: string;
                                        notes: string | null;
                                        metadata: {
                                            [key: string]: unknown;
                                        } | null;
                                        createdAt: string;
                                        updatedAt: string;
                                        deletedAt: string | null;
                                    };
                                };
                                scopeOfWork: {
                                    scopeOfWorkId: string;
                                    contractorId: string;
                                    jobId: string;
                                    notes: string | null;
                                    createdAt: string;
                                    updatedAt: string;
                                    lineItems: {
                                        sowLineItemId: string;
                                        scopeOfWorkId: string;
                                        description: string;
                                        price: number | null;
                                        startDate: string | null;
                                        endDate: string | null;
                                        contractor: string | null;
                                        isAllocation: boolean;
                                        sortOrder: number;
                                        createdAt: string;
                                        updatedAt: string;
                                    }[];
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Index: Record<string, never>;
        Signup: Record<string, never>;
        ForgotPassword: Record<string, never>;
        Me: Record<string, never>;
        "Login User": {
            a: string;
        };
        Logout: {
            a: string;
        };
        Jobs: Record<string, never>;
        Customers: Record<string, never>;
        Bids: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
