/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        companyName: string;
                        /** Format: email */
                        userEmail: string;
                        password: string;
                        referralCode?: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                user: {
                                    userId: string;
                                    email: string;
                                    companyId: string;
                                };
                                company: {
                                    companyName: string;
                                    companyId: string;
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                user: {
                                    userId: string;
                                    referralCode: string;
                                    companyId: string;
                                    /** @enum {string|null} */
                                    contractorType: "general" | "painter" | "plumber" | "electrician" | "carpenter" | "mason" | "landscaper" | "handyman" | "drywaller" | "framer" | "tileSetter" | "roofer" | "sidingInstaller" | "windowInstaller" | "doorInstaller" | "other";
                                    email: string;
                                    emailVerified: boolean;
                                    phoneNumber: string | null;
                                    phoneVerified: boolean;
                                    /** @enum {string|null} */
                                    preferredContactMethod: "email" | "phone" | "sms" | "whatsapp";
                                    firstName: string | null;
                                    lastName: string | null;
                                    is2FAEnabled: boolean | null;
                                    /** @enum {string|null} */
                                    lockReason: "tooManyFailedTFA" | "passwordResetCooldown";
                                    createdAt: string;
                                    /** @enum {string|null} */
                                    role: "admin" | "standard" | "view-only";
                                };
                                company: {
                                    companyId: string;
                                    companyName: string;
                                    email: string | null;
                                    phoneNumber: string | null;
                                    addressLine1: string | null;
                                    addressLine2: string | null;
                                    city: string | null;
                                    state: string | null;
                                    postalCode: string | null;
                                    notes: string | null;
                                    metadata: {
                                        [key: string]: unknown;
                                    } | null;
                                    createdAt: string;
                                    updatedAt: string;
                                };
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                        otp?: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: {
                                token?: string;
                                require2FA: boolean;
                            };
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login-user/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject: unknown;
                            statusCode: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Signup: Record<string, never>;
        Me: Record<string, never>;
        "Login User": {
            a: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
